# Generated by Django 3.1.12 on 2025-03-07 20:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20250306_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='usereventparticipation',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
